In [1]:
import pandas as pd

In [11]:
file = 'USDJPY_S1.csv'
df = pd.read_csv(file)
df

,_id,Time,Open,High,Low,Close,Volume
0,ObjectId(67d96c8538c23bc17e71ece0),2024-01-01T22:00:20.000Z,140.843,140.843,140.843,140.843,0.90
1,ObjectId(67d96c8538c23bc17e71ece1),2024-01-01T22:00:27.000Z,140.847,140.847,140.847,140.847,0.50
2,ObjectId(67d96c8538c23bc17e71ece2),2024-01-01T22:00:47.000Z,140.847,140.847,140.847,140.847,0.50
3,ObjectId(67d96c8538c23bc17e71ece3),2024-01-01T22:00:54.000Z,140.849,140.849,140.849,140.849,0.90
4,ObjectId(67d96c8538c23bc17e71ece4),2024-01-01T22:00:58.000Z,140.852,140.852,140.852,140.852,0.50
...,...,...,...,...,...,...,...
16128316,ObjectId(67d96cf338c23bc17e68061c),2025-03-17T23:59:48.000Z,149.392,149.392,149.392,149.392,1.20
16128317,ObjectId(67d96cf338c23bc17e68061d),2025-03-17T23:59:52.000Z,149.392,149.392,149.392,149.392,3.27
16128318,ObjectId(67d96cf338c23bc17e68061e),2025-03-17T23:59:53.000Z,149.394,149.394,149.394,149.394,3.09
16128319,ObjectId(67d96cf338c23bc17e68061f),2025-03-17T23:59:58.000Z,149.395,149.395,149.395,149.395,1.80
16128320,ObjectId(67d96cf338c23bc17e680620),2025-03-17T23:59:59.000Z,149.395,149.395,149.395,149.395,1.20

In [14]:
file2 = 'EURUSD_S1_export.csv'
df2 = pd.read_csv(file2)
df2

,Unnamed: 0,_id,Time,Open,High,Low,Close,Volume
0,0,67d9728738c23bc17e680621,2024-01-01 22:00:12,1.10427,1.10427,1.10427,1.10427,0.90
1,1,67d9728738c23bc17e680622,2024-01-01 22:00:14,1.10425,1.10425,1.10425,1.10425,0.90
2,2,67d9728738c23bc17e680623,2024-01-01 22:00:18,1.10425,1.10425,1.10425,1.10425,0.90
3,3,67d9728738c23bc17e680624,2024-01-01 22:00:25,1.10425,1.10425,1.10425,1.10425,0.90
4,4,67d9728738c23bc17e680625,2024-01-01 22:00:36,1.10429,1.10429,1.10429,1.10429,0.50
...,...,...,...,...,...,...,...,...
11042908,11042908,67d972a138c23bc17e10867d,2025-03-17 23:58:35,1.09182,1.09182,1.09181,1.09181,2.70
11042909,11042909,67d972a138c23bc17e10867e,2025-03-17 23:58:38,1.09183,1.09183,1.09183,1.09183,0.90
11042910,11042910,67d972a138c23bc17e10867f,2025-03-17 23:59:17,1.09182,1.09182,1.09182,1.09182,3.69
11042911,11042911,67d972a138c23bc17e108680,2025-03-17 23:59:28,1.09180,1.09180,1.09180,1.09180,0.90
11042912,11042912,67d972a138c23bc17e108681,2025-03-17 23:59:43,1.09180,1.09180,1.09180,1.09180,0.90

In [12]:
df['_id'] = df['_id'].str.extract(r'ObjectId\((.*?)\)')
df.reset_index(inplace=True)
df.rename(columns={'index': ''}, inplace=True)
df['Time'] = pd.to_datetime(df['Time']).dt.strftime('%Y-%m-%d %H:%M:%S')
df

,,_id,Time,Open,High,Low,Close,Volume
0,0,67d96c8538c23bc17e71ece0,2024-01-01 22:00:20,140.843,140.843,140.843,140.843,0.90
1,1,67d96c8538c23bc17e71ece1,2024-01-01 22:00:27,140.847,140.847,140.847,140.847,0.50
2,2,67d96c8538c23bc17e71ece2,2024-01-01 22:00:47,140.847,140.847,140.847,140.847,0.50
3,3,67d96c8538c23bc17e71ece3,2024-01-01 22:00:54,140.849,140.849,140.849,140.849,0.90
4,4,67d96c8538c23bc17e71ece4,2024-01-01 22:00:58,140.852,140.852,140.852,140.852,0.50
...,...,...,...,...,...,...,...,...
16128316,16128316,67d96cf338c23bc17e68061c,2025-03-17 23:59:48,149.392,149.392,149.392,149.392,1.20
16128317,16128317,67d96cf338c23bc17e68061d,2025-03-17 23:59:52,149.392,149.392,149.392,149.392,3.27
16128318,16128318,67d96cf338c23bc17e68061e,2025-03-17 23:59:53,149.394,149.394,149.394,149.394,3.09
16128319,16128319,67d96cf338c23bc17e68061f,2025-03-17 23:59:58,149.395,149.395,149.395,149.395,1.80
16128320,16128320,67d96cf338c23bc17e680620,2025-03-17 23:59:59,149.395,149.395,149.395,149.395,1.20

In [15]:
df.to_csv('USDJPY_S1_export.csv', index=False)